default:
  image: python:3.7
  before_script:
    #- apt-get -qq update
    #- apt-get -qq install -y python3-pip
    - pip install -r requirements.txt

print-help:
  script:
    - ./teachers_gitlab.sh help

install-print-help
  script:
    - ./setup.py build
    - ./setup.py install
    - teachers_gitlab help
